src/anvirali/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('add_order/', views.OrderCreateView.as_view(), name='add_order'),
    path('', views.IndexView.as_view(), name='index'),
    path('orders/<slug:order_slug>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('<int:order_id>/response/', views.ResponseAddView.as_view(), name='order_response'),
    path('orders/<slug:order_slug>/edit/', views.OrderEditView.as_view(), name='order_edit'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.SignedOutView.as_view(), name='logout'),
    path('register_customer/', views.register_customer, name='register_customer'),
    path('register_contractor/', views.register_contractor, name='register_contractor'),
    path('customer_personal_cabinet/', views.CustomerPersonalCabinetView.as_view(), name='customer_personal_cabinet'),
    path('contractor_personal_cabinet/',
         views.ContractorPersonalCabinetView.as_view(), name='contractor_personal_cabinet'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}anverali{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <header class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand">anverali</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            {% if user.customer %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:customer_personal_cabinet' %}">Личный кабинет</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'add_order' %}">Добавить заказ</a>
                            </li>
                            {% elif user.contractor %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:contractor_personal_cabinet' %}">Личный кабинет</a>
                            </li>
                            {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register_customer' %}">Регистрация заказчика</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register_contractor' %}">Регистрация исполнителя</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
                        </li>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <main class="container bg-gray">
        <br>
        {% block content %}
        {% endblock %}
        <br>
        <br>
    </main>

    <footer class="footer bg-dark text-light">
        <div class="container text-center">
            <p>&copy; {% now "Y" %}</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

src/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>